### ISSUE TITLE
missing translations when plural is used

### ISSUE THREAD

**Issue by myThorsten** [theLee3/flutter_auto_translator#21]
Thank you very much for providing flutter_auto_translator. It sure can save a lot of time.

Could you please tell me if I am doing something wrong? Here is a small app_en.arb for demonstration:

```
{
  "@@locale": "en",
  "@chat_nunber_of_unread_messages": {
    "placeholders": {
      "count": {
        "example": "55",
        "type": "int"
      }
    }
  },
  "chat": "Chat",
  "chat_hint_message": "Message",
  "chat_nunber_of_unread_messages": "{count, plural, zero{You have no unread messages.} one{You have an unread message.} other{You have {count} unread messages.}}"
}
```

When calling `flutter pub get && dart run auto_translator` I get this as result:

```
{
    "@@locale": "de",
    "chat": "{count, plural, zero{Sie haben keine ungelesenen Nachrichten.} one{Sie haben eine ungelesene Nachricht.} other{Sie haben {count} ungelesene Nachrichten.}}",
    "chat_hint_message": "Nachricht"
}
```

As you can see the translation for *chat_nunber_of_unread_messages* gets confused with that for *chat*.

*l10n.yaml* used:
```
arb-dir: lib/features/l10n/
output-dir: lib/features/l10n/
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: missing_translations.txt
nullable-getter: false
synthetic-package: false

# auto_translator
# - https://pub.dev/packages/auto_translator
# - flutter pub get && dart run auto_translator
translator:
  service: DeepL # Google
  targets:
    - de # deutsch
```
