### ISSUE TITLE
type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by santhosh-D-subramani** [theLee3/flutter_auto_translator#27]
```
C:\Users\h\AndroidStudioProjects\flutter1>flutter pub run auto_translator
Deprecated. Use `dart run` instead.
Building package executable...
Built auto_translator:auto_translator.
auto_translator v2.3.5
═════════════════════
No changes to app_en.arb
type 'Null' is not a subtype of type 'String' in type cast
Failed to update packages.
```

dont know why it happen , it was working fine a while ago

is there a way to find where this error poping up "type 'Null' is not a subtype of type 'String' in type cast" ??

**Comment by theLee3** [comment]
@santhosh-D-subramani Is it feasible for you to share your ARB file? Privately, if need be. Being able to recreate the issue with said ARB file would help me track down where this is occurring in the code and resolve the issue by ensuring more feedback is given.

**Comment by santhosh-D-subramani** [comment]
@theLee3 I have mailed to you through this support@leephillips.dev mail ID

**Comment by theLee3** [comment]
Thanks @santhosh-D-subramani. I will check it out.

**Comment by theLee3** [comment]
@santhosh-D-subramani I just translated your ARB without issue using both Google Translate and DeepL.

Could it be that you surpassed your quota? This should be handled more gracefully by the package, but that may be the issue. See if you are still getting the error, and let me know which service you are using.

I will still look into how the responses for each service or handled in such a case.

**Comment by MJ12358** [comment]
I'm getting this as well, quota does not seem to be an issue (Requests: 102) & (Current usage > 90% = 0).

**Comment by MJ12358** [comment]
@theLee3 I've emailed you my ARB.
It's super simple, just a bunch of key-value pairs.
This was working a one point but no longer.

l10n.yaml
```yaml
arb-dir: l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n
nullable-getter: false
synthetic-package: false
untranslated-messages-file: l10n/untranslated.txt

translator:
  service: Google
  key_file: service_accounts/translate-api-key
  targets:
    - ar
    - de
    - es
    - fr
    - ko
    - ru
    - vi
    - zh

```

**Comment by theLee3** [comment]
@MJ12358 Thank you! I'm on it.

**Comment by MJ12358** [comment]
This is interesting, I'm not seeing any metrics within GCP. All result in "No data is available...".
I'm wondering if there is an issue elsewhere (Flutter/Dart update?).

flutter doctor -v
``` bash
[√] Flutter (Channel stable, 3.32.6, on Microsoft Windows [Version 10.0.17763.6775], locale en-US) [461ms]
    • Flutter version 3.32.6 on channel stable at C:\Portable Apps\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 077b4a4ce1 (7 days ago), 2025-07-08 13:31:08 -0700
    • Engine revision 72f2b18bb0
    • Dart version 3.8.1
    • DevTools version 2.45.1

[√] Windows Version (10 Enterprise N LTSC 64-bit, 1809) [1,156ms]

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.3s]
    • Android SDK at C:\Android\android-sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[√] Chrome - develop for the web [28ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2024.3.2) [26ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[√] VS Code, 64-bit edition (version 1.101.2) [24ms]
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.114.0

[√] Connected device (1 available) [210ms]
    • Chrome (web) • chrome • web-javascript • Google Chrome 138.0.7204.101

[√] Network resources [293ms]
    • All expected network resources are available.

• No issues found!
```

**Comment by theLee3** [comment]
I see nothing inherently wrong there.

I believe the issue is that the quota reporting is leading to confusion. GCP does not actually use the monthly quota in its reporting models. You would have to set up a policy to report/alert you to usage at or near the monthly limit (500k characters).

Please follow these steps to see what your actually usage has been over the last 30 days:
1. Go to APIs & Services > Enabled APIs & Services.
2. Select Cloud Translation API.
3. Then select the Quotas & System Limits tab. (Same place you looked previously)
4. Find the "v2 and v3 general model characters per day" and select the "show usage chart" button to the right.
5. Then select "30 days" at the top.

**Comment by MJ12358** [comment]
Nothing here either:
`v2 and v3 general model characters per day` -> `30 days` -> "No data is available for the selected time frame"

**Comment by theLee3** [comment]
@MJ12358 I'm sorry it took a little longer than I had hoped to get it published, but the `verbose` branch is now ready for you to try. Please update `pubspec.yaml` as follows.

```yaml
auto_translator:
    git:
      url: https://github.com/theLee3/flutter_auto_translator
      branch: verbose
```

Run with the verbose flag: `dart run auto_translator -v`

This will print to console each request and response payload that `auto_translator` makes and receives for either service that is used, along with some more information about some steps along the way.

Please let me know what you discover.

**Comment by MJ12358** [comment]
When running `dart run auto_translator -v` I'm getting `FormatException: Could not find an option or flag "-v".`

pubspec.yaml
```yaml
dev_dependencies:
  auto_translator:
    git:
      url: https://github.com/theLee3/flutter_auto_translator
      branch: verbose
```

I ran `flutter clean` just in case but still get this error.

**Comment by theLee3** [comment]
Please run it without the flag (without letting it actually translate anything for quota's sake) and ensure that it says version 2.3.6

**Comment by MJ12358** [comment]
Says `auto_translator v2.3.5`

**Comment by theLee3** [comment]
Sorry, I misremembered the key 🙃. Change `branch` to `ref`.

```yaml
dev_dependencies:
  auto_translator:
    git:
      url: https://github.com/theLee3/flutter_auto_translator
      ref: verbose
```
